version: "3"
services:
  api:
    container_name: "pipenv-docker-dev-api"
    build:
      context: .
      dockerfile: "Dockerfile.dev"
    restart: always
    tty: true
    ports:
      - "127.0.0.1:8001:8001"
    volumes:
      - .:/app
